blank_issues_enabled: true
contact_links:
  - name: BombSquad Community Server Discord
    url: https://discord.com/invite/ucyaesh
    about: Please ask and answer questions here.
  - name: BombSquad/Ballistica Official Discord
    url: https://ballistica.net/discord
    about: Please ask and answer questions here.
